"use client";

import { useEffect, useState, type FormEvent } from "react";
import { warehouseApi, type CarrierReceipt, type CatalogItem, type PurchaseOrder, type PurchaseOrderLine } from "@/lib/api/warehouse";
import { button, EvidencePicker, Field, input, panel } from "../Ui";

export function CountForm({ carriers, warehouses, onSave }: { carriers: CarrierReceipt[]; warehouses: CatalogItem[]; onSave: (body: Record<string, unknown>) => void }) {
  const [carrierId, setCarrierId] = useState(""); const [carrier, setCarrier] = useState<CarrierReceipt | null>(null); const [po, setPo] = useState<PurchaseOrder | null>(null); const [warehouseId, setWarehouseId] = useState(""); const [count, setCount] = useState<Record<number,{ good: string; damaged: string; wrong: string; serials: string }>>({}); const [title, setTitle] = useState(""); const [detail, setDetail] = useState(""); const [mediaIds, setMediaIds] = useState<number[]>([]);
  useEffect(() => {
    if (!carrierId) return;
    const controller = new AbortController();
    void warehouseApi.carrierReceipt(Number(carrierId), controller.signal)
      .then(async (item) => {
        const order = await warehouseApi.purchaseOrder(item.purchase_order_id, controller.signal);
        if (!controller.signal.aborted) { setCarrier(item); setPo(order); }
      }).catch(() => undefined);
    return () => controller.abort();
  }, [carrierId]);
  const lines = po?.lines?.filter((line) => { const item = count[line.id]; return item && Number(item.good || 0) + Number(item.damaged || 0) + Number(item.wrong || 0) > 0; }) ?? [];
  const damaged = lines.some((line) => Number(count[line.id].damaged || 0) + Number(count[line.id].wrong || 0) > 0);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!carrier || !lines.length) return; onSave({ carrierReceiptId: carrier.id, warehouseId: Number(warehouseId), lines: lines.map((line) => ({ purchaseOrderLineId: line.id, goodQuantity: count[line.id].good || "0", damagedQuantity: count[line.id].damaged || "0", wrongQuantity: count[line.id].wrong || "0", serialNumbers: count[line.id].serials.split(/[,\n]/).map((item) => item.trim()).filter(Boolean) })), issueTitle: damaged ? title : undefined, issueDetail: damaged ? detail : undefined, mediaAssetIds: mediaIds }); };
  return <form className={`${panel} space-y-3 self-start`} onSubmit={submit}><h2 className="text-lg font-bold">เปิดกล่องและนับจริง</h2><Field label="ใบขนส่งที่ยืนยันรับแล้ว"><select className={input} required value={carrierId} onChange={(event) => { setCarrier(null); setPo(null); setCarrierId(event.target.value); }}><option value="">เลือกใบขนส่ง</option>{carriers.filter((item) => item.received_at).map((item) => <option key={item.id} value={item.id}>{item.record_no} · {item.purchase_order_no}</option>)}</select></Field>{carrier?.confirmation && <Field label="คลังปลายทางในสาขาที่รับ"><select className={input} required value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)}><option value="">เลือกคลัง</option>{warehouses.filter((item) => item.active !== false && item.branch_id === carrier.confirmation?.receiving_branch_id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>}{po?.lines?.map((line: PurchaseOrderLine) => <div key={line.id} className="space-y-2 rounded-xl border border-slate-200 p-3 dark:border-white/10"><strong>{line.sku} · {line.product_name}</strong><p className="text-xs text-slate-500">สั่ง {line.quantity} · ยังขาดของดี {line.remaining_good_quantity}</p><div className="grid grid-cols-3 gap-2">{([ ["good", "ดี"], ["damaged", "ชำรุด"], ["wrong", "ผิดรุ่น"] ] as const).map(([key,label]) => <Field key={key} label={label}><input className={input} type="number" min="0" step="0.001" value={count[line.id]?.[key] ?? ""} onChange={(event) => setCount({ ...count, [line.id]: { good: count[line.id]?.good ?? "", damaged: count[line.id]?.damaged ?? "", wrong: count[line.id]?.wrong ?? "", serials: count[line.id]?.serials ?? "", [key]: event.target.value } })} /></Field>)}</div><Field label="Serial ของดี (คั่นด้วยจุลภาค)"><textarea className={input} value={count[line.id]?.serials ?? ""} onChange={(event) => setCount({ ...count, [line.id]: { good: count[line.id]?.good ?? "", damaged: count[line.id]?.damaged ?? "", wrong: count[line.id]?.wrong ?? "", serials: event.target.value } })} /></Field></div>)}{damaged && <><Field label="หัวเรื่องปัญหา"><input className={input} required value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="รายละเอียดปัญหา"><textarea className={input} required value={detail} onChange={(event) => setDetail(event.target.value)} /></Field><EvidencePicker required onChange={setMediaIds} /></>}<button className={button} disabled={!carrier?.confirmation || !warehouseId || !lines.length || (damaged && !mediaIds.length)}>บันทึกผลนับ</button><p className="text-xs text-slate-500">จำนวนชำรุดและผิดรุ่นจะไม่เพิ่มสต๊อก</p></form>;
}
