"use client";

import { useState, type FormEvent } from "react";
import type { CatalogItem, PurchaseOrder } from "@/lib/api/warehouse";
import { button, Field, input, panel, subtleButton } from "../Ui";
import { ProductSearchSelect } from "../ProductSearchSelect";

export function PoDetails({ po, canClose, onEdit, onClose }: { po: PurchaseOrder; canClose: boolean; onEdit: (body: Record<string, unknown>) => void; onClose: () => void }) {
  const [date, setDate] = useState(po.ordered_at?.slice(0,10) ?? ""); const [note, setNote] = useState(po.note ?? "");
  const editable = !po.closed_at && !po.supplierReceipts?.length && !po.carrierReceipts?.length;
  return <div className="mt-5 space-y-3 rounded-xl bg-slate-50 p-4 text-sm dark:bg-white/5"><h3 className="font-bold">{po.record_no} · {po.supplier_name}</h3><p>วันที่สั่ง {po.ordered_at?.slice(0,10)} · ผู้สั่งจริง: CEO #{po.ordered_by_ceo_id}</p>{po.lines?.map((line) => <div key={line.id} className="flex justify-between gap-2 border-t border-slate-200 pt-2 dark:border-white/10"><span>{line.sku} · {line.product_name}</span><span>สั่ง {line.quantity} / ดี {line.counted_good_quantity} / ค้าง {line.remaining_good_quantity}</span></div>)}<p className="text-xs text-slate-500">ผู้กรอกเอกสารกับ CEO ผู้สั่งซื้อเป็นคนละข้อมูล</p>{editable && <form className="space-y-2 border-t border-slate-200 pt-3 dark:border-white/10" onSubmit={(event) => { event.preventDefault(); onEdit({ orderedAt: date, note: note || null }); }}><Field label="แก้วันที่สั่ง"><input className={input} type="date" required value={date} onChange={(event) => setDate(event.target.value)} /></Field><Field label="แก้หมายเหตุ"><textarea className={input} value={note} onChange={(event) => setNote(event.target.value)} /></Field><button className={subtleButton}>บันทึกการแก้ไข</button></form>}{canClose && !po.closed_at && <button className="text-sm font-medium text-rose-600 underline" onClick={() => { if (window.confirm(`ปิด PO ${po.record_no}?`)) onClose(); }}>ปิด PO</button>}</div>;
}

export function PoForm({ suppliers, ceos, onSave }: { suppliers: CatalogItem[]; ceos: Array<{ id: number; name: string }>; onSave: (body: Record<string, unknown>) => void }) {
  const [supplierId, setSupplierId] = useState(""); const [ceoId, setCeoId] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0,10)); const [note, setNote] = useState("");
  const [lines, setLines] = useState([{ productId: "", quantity: "", unitPrice: "" }]);
  const submit = (event: FormEvent) => { event.preventDefault(); onSave({ supplierId: Number(supplierId), orderedByCeoId: Number(ceoId), orderedAt: date, note: note || null, lines: lines.map((line) => ({ productId: Number(line.productId), quantity: line.quantity, unitPrice: line.unitPrice })) }); };
  return <form className={`${panel} space-y-3 self-start`} onSubmit={submit}><h2 className="text-lg font-bold">บันทึก PO ที่ CEO สั่ง</h2><Field label="ผู้ขาย"><select className={input} required value={supplierId} onChange={(event) => setSupplierId(event.target.value)}><option value="">เลือกผู้ขาย</option>{suppliers.filter((item) => item.active !== false).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="CEO ผู้สั่งซื้อจริง"><select className={input} required value={ceoId} onChange={(event) => setCeoId(event.target.value)}><option value="">เลือก CEO</option>{ceos.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="วันที่สั่ง"><input className={input} type="date" required value={date} onChange={(event) => setDate(event.target.value)} /></Field>{lines.map((line,index) => <div key={index} className="space-y-2 rounded-xl border border-slate-200 p-3 dark:border-white/10"><ProductSearchSelect value={line.productId} onChange={(value) => setLines(lines.map((item,i) => i === index ? { ...item, productId: value } : item))} /><div className="grid grid-cols-2 gap-2"><input className={input} type="number" min="0.001" step="0.001" placeholder="จำนวน" required value={line.quantity} onChange={(event) => setLines(lines.map((item,i) => i === index ? { ...item, quantity: event.target.value } : item))} /><input className={input} type="number" min="0" step="0.01" placeholder="ราคา/หน่วย" required value={line.unitPrice} onChange={(event) => setLines(lines.map((item,i) => i === index ? { ...item, unitPrice: event.target.value } : item))} /></div>{lines.length > 1 && <button type="button" className="text-sm text-rose-600" onClick={() => setLines(lines.filter((_,i) => i !== index))}>ลบบรรทัด</button>}</div>)}<button type="button" className={subtleButton} onClick={() => setLines([...lines, { productId: "", quantity: "", unitPrice: "" }])}>เพิ่มสินค้า</button><Field label="หมายเหตุ"><textarea className={input} value={note} onChange={(event) => setNote(event.target.value)} /></Field><button className={button} disabled={!suppliers.length || !ceos.length}>บันทึก PO</button></form>;
}
