import { ValidationError } from "@/lib/core/http/errors";import { parsePageRequest } from "@/lib/core/http/pagination";import { isBigIntId } from "@/lib/core/ids/bigint";import { optionalBigIntId,optionalText,rejectUnknownFields,requiredBigIntId,requiredBoolean,requiredInteger,requiredText } from "@/lib/core/validation/fields";import type { PickingStrategy,ProductFilters,ProductInput,ProductUpdateInput,TrackingMethod } from "@/lib/products/types";
const fields=["sku","nameTh","nameEn","description","categoryId","brandId","baseUnitId","trackingMethod","pickingStrategy","weightKg","lengthCm","widthCm","heightCm","standardCost","currencyCode","shelfLifeDays","storageCondition","isActive"] as const;const decimal=/^(?:0|[1-9]\d*)(?:\.\d+)?$/;
function sku(b:Record<string,unknown>){const v=requiredText(b,"sku").toUpperCase();if(!/^[A-Z0-9][A-Z0-9._-]{0,63}$/.test(v))throw new ValidationError({sku:"Use up to 64 uppercase letters, numbers, dots, underscores, or hyphens."});return v;}
function tracking(b:Record<string,unknown>){const v=requiredText(b,"trackingMethod").toUpperCase() as TrackingMethod;if(!["NONE","LOT","SERIAL"].includes(v))throw new ValidationError({trackingMethod:"Use NONE, LOT, or SERIAL."});return v;}
function picking(b:Record<string,unknown>){const v=requiredText(b,"pickingStrategy").toUpperCase() as PickingStrategy;if(v!=="FIFO"&&v!=="FEFO")throw new ValidationError({pickingStrategy:"Use FIFO or FEFO."});return v;}
function dec(b:Record<string,unknown>,k:string){const v=optionalText(b,k);if(v!==null&&(!decimal.test(v)||Number(v)<=0))throw new ValidationError({[k]:"Use a positive decimal string or null."});return v;}
function shelf(b:Record<string,unknown>){const v=b.shelfLifeDays;if(v===undefined||v===null)return null;if(!Number.isInteger(v)||(v as number)<=0||(v as number)>36500)throw new ValidationError({shelfLifeDays:"Use a positive integer or null."});return v as number;}
function currency(b:Record<string,unknown>){const v=requiredText(b,"currencyCode").toUpperCase();if(!/^[A-Z]{3}$/.test(v))throw new ValidationError({currencyCode:"Use an uppercase ISO three-letter currency code."});return v;}
function validateRules<T extends Partial<ProductInput>>(o:T){if(o.pickingStrategy==="FEFO"&&o.trackingMethod!=="LOT")throw new ValidationError({pickingStrategy:"FEFO requires LOT tracking."});if(o.trackingMethod==="LOT"&&o.pickingStrategy==="FEFO"&&!o.shelfLifeDays)throw new ValidationError({shelfLifeDays:"A positive shelf life is required for FEFO."});return o;}
export function parseCreateProduct(b:Record<string,unknown>):ProductInput{rejectUnknownFields(b,fields);return validateRules({sku:sku(b),nameTh:requiredText(b,"nameTh"),nameEn:optionalText(b,"nameEn"),description:optionalText(b,"description"),categoryId:optionalBigIntId(b,"categoryId"),brandId:optionalBigIntId(b,"brandId"),baseUnitId:requiredBigIntId(b,"baseUnitId"),trackingMethod:tracking(b),pickingStrategy:picking(b),weightKg:dec(b,"weightKg"),lengthCm:dec(b,"lengthCm"),widthCm:dec(b,"widthCm"),heightCm:dec(b,"heightCm"),standardCost:dec(b,"standardCost"),currencyCode:currency(b),shelfLifeDays:shelf(b),storageCondition:optionalText(b,"storageCondition"),isActive:requiredBoolean(b,"isActive")});}
export function parseUpdateProduct(b:Record<string,unknown>):ProductUpdateInput{rejectUnknownFields(b,[...fields,"version"]);const o:ProductUpdateInput={version:requiredInteger(b,"version",1,2147483647)};if(b.sku!==undefined)o.sku=sku(b);if(b.nameTh!==undefined)o.nameTh=requiredText(b,"nameTh");if(b.nameEn!==undefined)o.nameEn=optionalText(b,"nameEn");if(b.description!==undefined)o.description=optionalText(b,"description");if(b.categoryId!==undefined)o.categoryId=optionalBigIntId(b,"categoryId");if(b.brandId!==undefined)o.brandId=optionalBigIntId(b,"brandId");if(b.baseUnitId!==undefined)o.baseUnitId=requiredBigIntId(b,"baseUnitId");if(b.trackingMethod!==undefined)o.trackingMethod=tracking(b);if(b.pickingStrategy!==undefined)o.pickingStrategy=picking(b);for(const k of ["weightKg","lengthCm","widthCm","heightCm","standardCost"] as const)if(b[k]!==undefined)o[k]=dec(b,k);if(b.currencyCode!==undefined)o.currencyCode=currency(b);if(b.shelfLifeDays!==undefined)o.shelfLifeDays=shelf(b);if(b.storageCondition!==undefined)o.storageCondition=optionalText(b,"storageCondition");if(b.isActive!==undefined)o.isActive=requiredBoolean(b,"isActive");if(Object.keys(o).length===1)throw new ValidationError({body:"Provide at least one field to update."});return o;}
export function parseProductFilters(url:URL):ProductFilters{const categoryId=url.searchParams.get("categoryId"),brandId=url.searchParams.get("brandId");if(categoryId&&!isBigIntId(categoryId))throw new ValidationError({categoryId:"Use a positive integer ID."});if(brandId&&!isBigIntId(brandId))throw new ValidationError({brandId:"Use a positive integer ID."});const rawTracking=url.searchParams.get("trackingMethod")?.toUpperCase() as TrackingMethod|undefined;if(rawTracking&&!["NONE","LOT","SERIAL"].includes(rawTracking))throw new ValidationError({trackingMethod:"Use NONE, LOT, or SERIAL."});const rawActive=url.searchParams.get("active");if(rawActive!==null&&rawActive!=="true"&&rawActive!=="false")throw new ValidationError({active:"Use true or false."});return{search:url.searchParams.get("search")?.trim().replace(/([%_\\])/g,"\\$1")||null,categoryId,brandId,trackingMethod:rawTracking??null,active:rawActive===null?null:rawActive==="true",page:parsePageRequest(url)};}
