BEGIN;

SELECT pg_advisory_xact_lock(hashtext('dawh_p0_frontend_handoff'));

DO $$
BEGIN
  IF (SELECT count(*) FROM public.organizations WHERE is_active) <> 1 THEN
    RAISE EXCEPTION 'P0 patch requires exactly one active organization';
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  code text NOT NULL CHECK (btrim(code) <> ''),
  name text NOT NULL CHECK (btrim(name) <> ''),
  is_active boolean NOT NULL DEFAULT true,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (id, organization_id),
  UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS public.user_access_controls (
  user_id text PRIMARY KEY REFERENCES public."user" (id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'SUSPENDED', 'TERMINATED')),
  reason text,
  changed_at timestamptz NOT NULL DEFAULT now(),
  changed_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS departments_set_updated_at ON public.departments;
CREATE TRIGGER departments_set_updated_at
BEFORE UPDATE ON public.departments
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS user_access_controls_set_updated_at ON public.user_access_controls;
CREATE TRIGGER user_access_controls_set_updated_at
BEFORE UPDATE ON public.user_access_controls
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_access_controls ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.departments FROM anon, authenticated;
REVOKE ALL ON TABLE public.user_access_controls FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.departments_id_seq FROM anon, authenticated;

ALTER TABLE public.employee_profiles
  ADD COLUMN IF NOT EXISTS facility_id bigint REFERENCES public.facilities (id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS department_id bigint REFERENCES public.departments (id) ON DELETE SET NULL;

ALTER TABLE public.user_facility_scopes
  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1 CHECK (version > 0);

CREATE INDEX IF NOT EXISTS employee_profiles_facility_id_idx
  ON public.employee_profiles (facility_id);
CREATE INDEX IF NOT EXISTS employee_profiles_department_id_idx
  ON public.employee_profiles (department_id);
CREATE INDEX IF NOT EXISTS departments_organization_active_idx
  ON public.departments (organization_id, is_active, code);
CREATE INDEX IF NOT EXISTS departments_created_by_idx
  ON public.departments (created_by);
CREATE INDEX IF NOT EXISTS departments_updated_by_idx
  ON public.departments (updated_by);
CREATE INDEX IF NOT EXISTS user_access_controls_status_idx
  ON public.user_access_controls (status);
CREATE INDEX IF NOT EXISTS user_access_controls_changed_by_idx
  ON public.user_access_controls (changed_by);

UPDATE public.employee_profiles AS profile
SET facility_id = facility.id
FROM public.facilities AS facility
JOIN public.organizations AS organization
  ON organization.id = facility.organization_id
WHERE profile.facility_id IS NULL
  AND organization.is_active
  AND facility.is_active
  AND facility.code = profile.branch_code;

INSERT INTO public.roles (code, name, description, is_system, is_active)
VALUES
  ('SYSTEM_ADMINISTRATOR', 'System Administrator', 'Full system access', true, true),
  ('HQ_AREA_MANAGER', 'HQ / Area Manager', 'Multi-facility oversight and approvals', true, true),
  ('WAREHOUSE_MANAGER', 'Warehouse Manager', 'Warehouse approvals and operations', true, true),
  ('STOCK_CONTROLLER', 'Stock Controller', 'Receiving, putaway, movement, and stock control', true, true),
  ('PICKER_PACKER', 'Picker / Packer', 'Picking and packing operations', true, true),
  ('BRANCH_REQUESTER', 'Branch Requester', 'Branch stock requests and transfer tracking', true, true),
  ('BRANCH_RECEIVER', 'Branch Receiver', 'Destination receiving and claim intake', true, true),
  ('CLAIM_OFFICER', 'Claim Officer', 'Claim investigation and resolution', true, true),
  ('AUDITOR', 'Auditor', 'Read-only reporting and audit access', true, true)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  is_system = true,
  is_active = true,
  updated_at = now();

WITH canonical_roles AS (
  SELECT id FROM public.roles
  WHERE code IN (
    'SYSTEM_ADMINISTRATOR', 'HQ_AREA_MANAGER', 'WAREHOUSE_MANAGER',
    'STOCK_CONTROLLER', 'PICKER_PACKER', 'BRANCH_REQUESTER',
    'BRANCH_RECEIVER', 'CLAIM_OFFICER', 'AUDITOR'
  )
)
DELETE FROM public.role_permissions
WHERE role_id IN (SELECT id FROM canonical_roles);

WITH role_grants (role_code, permission_code) AS (
  SELECT 'SYSTEM_ADMINISTRATOR', code
  FROM public.permissions
  WHERE is_active
  UNION ALL VALUES
    ('HQ_AREA_MANAGER', 'admin.facilities.read'),
    ('HQ_AREA_MANAGER', 'admin.products.read'),
    ('HQ_AREA_MANAGER', 'product.read'),
    ('HQ_AREA_MANAGER', 'stock.read'),
    ('HQ_AREA_MANAGER', 'stock.ledger.read'),
    ('HQ_AREA_MANAGER', 'transfer.read'),
    ('HQ_AREA_MANAGER', 'transfer.create'),
    ('HQ_AREA_MANAGER', 'transfer.approve'),
    ('HQ_AREA_MANAGER', 'shipment.read'),
    ('HQ_AREA_MANAGER', 'shipment.manage'),
    ('HQ_AREA_MANAGER', 'receipt.read'),
    ('HQ_AREA_MANAGER', 'claim.read'),
    ('HQ_AREA_MANAGER', 'claim.manage'),
    ('HQ_AREA_MANAGER', 'report.read'),
    ('HQ_AREA_MANAGER', 'notification.read'),
    ('WAREHOUSE_MANAGER', 'product.read'),
    ('WAREHOUSE_MANAGER', 'stock.read'),
    ('WAREHOUSE_MANAGER', 'stock.ledger.read'),
    ('WAREHOUSE_MANAGER', 'stock.receive'),
    ('WAREHOUSE_MANAGER', 'stock.putaway'),
    ('WAREHOUSE_MANAGER', 'stock.move'),
    ('WAREHOUSE_MANAGER', 'stock.adjust.request'),
    ('WAREHOUSE_MANAGER', 'stock.adjust.approve'),
    ('WAREHOUSE_MANAGER', 'stock.count'),
    ('WAREHOUSE_MANAGER', 'transfer.read'),
    ('WAREHOUSE_MANAGER', 'transfer.create'),
    ('WAREHOUSE_MANAGER', 'transfer.approve'),
    ('WAREHOUSE_MANAGER', 'transfer.dispatch'),
    ('WAREHOUSE_MANAGER', 'pick.read'),
    ('WAREHOUSE_MANAGER', 'pick.operate'),
    ('WAREHOUSE_MANAGER', 'pack.read'),
    ('WAREHOUSE_MANAGER', 'pack.operate'),
    ('WAREHOUSE_MANAGER', 'shipment.read'),
    ('WAREHOUSE_MANAGER', 'shipment.manage'),
    ('WAREHOUSE_MANAGER', 'report.read'),
    ('WAREHOUSE_MANAGER', 'notification.read'),
    ('STOCK_CONTROLLER', 'product.read'),
    ('STOCK_CONTROLLER', 'stock.read'),
    ('STOCK_CONTROLLER', 'stock.ledger.read'),
    ('STOCK_CONTROLLER', 'stock.receive'),
    ('STOCK_CONTROLLER', 'stock.putaway'),
    ('STOCK_CONTROLLER', 'stock.move'),
    ('STOCK_CONTROLLER', 'stock.adjust.request'),
    ('STOCK_CONTROLLER', 'stock.count'),
    ('STOCK_CONTROLLER', 'transfer.read'),
    ('STOCK_CONTROLLER', 'notification.read'),
    ('PICKER_PACKER', 'product.read'),
    ('PICKER_PACKER', 'stock.read'),
    ('PICKER_PACKER', 'transfer.read'),
    ('PICKER_PACKER', 'pick.read'),
    ('PICKER_PACKER', 'pick.operate'),
    ('PICKER_PACKER', 'pack.read'),
    ('PICKER_PACKER', 'pack.operate'),
    ('PICKER_PACKER', 'shipment.read'),
    ('PICKER_PACKER', 'notification.read'),
    ('BRANCH_REQUESTER', 'product.read'),
    ('BRANCH_REQUESTER', 'stock.read'),
    ('BRANCH_REQUESTER', 'transfer.read'),
    ('BRANCH_REQUESTER', 'transfer.create'),
    ('BRANCH_REQUESTER', 'notification.read'),
    ('BRANCH_RECEIVER', 'product.read'),
    ('BRANCH_RECEIVER', 'stock.read'),
    ('BRANCH_RECEIVER', 'transfer.read'),
    ('BRANCH_RECEIVER', 'transfer.receive'),
    ('BRANCH_RECEIVER', 'receipt.read'),
    ('BRANCH_RECEIVER', 'receipt.manage'),
    ('BRANCH_RECEIVER', 'claim.read'),
    ('BRANCH_RECEIVER', 'claim.manage'),
    ('BRANCH_RECEIVER', 'notification.read'),
    ('CLAIM_OFFICER', 'product.read'),
    ('CLAIM_OFFICER', 'stock.read'),
    ('CLAIM_OFFICER', 'transfer.read'),
    ('CLAIM_OFFICER', 'shipment.read'),
    ('CLAIM_OFFICER', 'receipt.read'),
    ('CLAIM_OFFICER', 'claim.read'),
    ('CLAIM_OFFICER', 'claim.manage'),
    ('CLAIM_OFFICER', 'report.read'),
    ('CLAIM_OFFICER', 'notification.read'),
    ('AUDITOR', 'product.read'),
    ('AUDITOR', 'stock.read'),
    ('AUDITOR', 'stock.ledger.read'),
    ('AUDITOR', 'transfer.read'),
    ('AUDITOR', 'shipment.read'),
    ('AUDITOR', 'receipt.read'),
    ('AUDITOR', 'claim.read'),
    ('AUDITOR', 'report.read'),
    ('AUDITOR', 'audit.read')
)
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT role.id, permission.id
FROM role_grants AS grant_row
JOIN public.roles AS role ON role.code = grant_row.role_code
JOIN public.permissions AS permission
  ON permission.code = grant_row.permission_code
 AND permission.is_active
ON CONFLICT (role_id, permission_id) DO NOTHING;

WITH legacy_map (legacy_code, canonical_code) AS (
  VALUES
    ('WAREHOUSE_ADMINISTRATOR', 'HQ_AREA_MANAGER'),
    ('WAREHOUSE_STAFF', 'STOCK_CONTROLLER'),
    ('BRANCH_ADMINISTRATOR', 'BRANCH_REQUESTER'),
    ('BRANCH_MANAGER', 'BRANCH_REQUESTER'),
    ('BRANCH_STAFF', 'BRANCH_RECEIVER')
)
INSERT INTO public.user_role_assignments (
  user_id,
  role_id,
  valid_from,
  valid_until,
  assigned_at,
  assigned_by
)
SELECT
  assignment.user_id,
  canonical.id,
  assignment.valid_from,
  assignment.valid_until,
  assignment.assigned_at,
  assignment.assigned_by
FROM public.user_role_assignments AS assignment
JOIN public.roles AS legacy ON legacy.id = assignment.role_id
JOIN legacy_map AS mapping ON mapping.legacy_code = legacy.code
JOIN public.roles AS canonical ON canonical.code = mapping.canonical_code
WHERE assignment.revoked_at IS NULL
ON CONFLICT (user_id, role_id) WHERE revoked_at IS NULL DO NOTHING;

WITH legacy_codes (code) AS (
  VALUES
    ('WAREHOUSE_ADMINISTRATOR'),
    ('WAREHOUSE_STAFF'),
    ('BRANCH_ADMINISTRATOR'),
    ('BRANCH_MANAGER'),
    ('BRANCH_STAFF')
)
UPDATE public.user_role_assignments AS assignment
SET
  revoked_at = now(),
  revoke_reason = 'Replaced by canonical P0 role catalog'
FROM public.roles AS role
JOIN legacy_codes ON legacy_codes.code = role.code
WHERE assignment.role_id = role.id
  AND assignment.revoked_at IS NULL;

UPDATE public.roles AS role
SET is_active = false, updated_at = now()
WHERE role.code IN (
  'WAREHOUSE_ADMINISTRATOR', 'WAREHOUSE_STAFF', 'BRANCH_ADMINISTRATOR',
  'BRANCH_MANAGER', 'BRANCH_STAFF', 'DRIVER'
)
AND NOT EXISTS (
  SELECT 1
  FROM public.user_role_assignments AS assignment
  WHERE assignment.role_id = role.id
    AND assignment.revoked_at IS NULL
    AND (assignment.valid_from IS NULL OR assignment.valid_from <= now())
    AND (assignment.valid_until IS NULL OR assignment.valid_until > now())
);

COMMIT;
