"use client";

import { useCallback, useState } from "react";
import WarehousePageTemplate from "@/app/warehouse/_components/WarehousePageTemplate";
import { warehouseApi } from "@/lib/api/warehouse";
import { button, Empty, Notice, panel, subtleButton, useRemote } from "./Ui";

export default function ReportsScreen() {
  const [tab, setTab] = useState<"outstanding" | "receipts">("outstanding");
  const load = useCallback(() => Promise.all([warehouseApi.outstandingReport(), warehouseApi.receiptReport()]), []);
  const { data, loading, error } = useRemote(load);
  const [outstanding, receipts] = data ?? [[], []];
  return <WarehousePageTemplate titleEn="Reports" titleTh="รายงานคลังสินค้า" routePath="/warehouse/reports" iconName="history"><div className="flex gap-2"><button className={tab === "outstanding" ? button : subtleButton} onClick={() => setTab("outstanding")}>PO ค้างรับ</button><button className={tab === "receipts" ? button : subtleButton} onClick={() => setTab("receipts")}>ประวัติรับสินค้า</button></div>{loading && <p>กำลังโหลดรายงาน...</p>}{error && <Notice tone="error">{error}</Notice>}<section className={panel}>{tab === "outstanding" ? <><h2 className="mb-4 text-lg font-bold">สินค้าดีที่ยังขาดจาก PO</h2>{outstanding.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 dark:border-white/10"><th className="pb-2">PO / ผู้ขาย</th><th>สินค้า</th><th className="text-right">สั่ง</th><th className="text-right">นับดี</th><th className="text-right">ลงสต๊อก</th><th className="text-right">ค้างรับ</th></tr></thead><tbody>{outstanding.map((item,index) => <tr key={`${item.purchase_order_id}-${index}`} className="border-b border-slate-100 dark:border-white/10"><td className="py-3">{item.purchase_order_no}<small className="block text-slate-500">{item.supplier_name}</small></td><td>{item.sku} · {item.product_name}</td><td className="text-right">{item.ordered_quantity}</td><td className="text-right">{item.counted_good_quantity}</td><td className="text-right">{item.posted_good_quantity}</td><td className="text-right font-semibold text-amber-600">{item.remaining_good_quantity}</td></tr>)}</tbody></table></div> : <Empty text="ไม่มี PO ค้างรับ" />}</> : <><h2 className="mb-4 text-lg font-bold">ประวัติรับสินค้า</h2>{receipts.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 dark:border-white/10"><th className="pb-2">เอกสาร</th><th>สาขา / คลัง</th><th>สินค้า</th><th className="text-right">ดี</th><th className="text-right">ชำรุด</th><th>สถานะ</th></tr></thead><tbody>{receipts.map((item,index) => <tr key={index} className="border-b border-slate-100 dark:border-white/10"><td className="py-3">{String(item.goods_receipt_no ?? "")}</td><td>{String(item.branch_name ?? "")} / {String(item.warehouse_name ?? "")}</td><td>{String(item.sku ?? "")} · {String(item.product_name ?? "")}</td><td className="text-right">{String(item.good_quantity ?? "0")}</td><td className="text-right">{String(item.damaged_quantity ?? "0")}</td><td>{item.posted_at ? "ลงสต๊อกแล้ว" : "รอลงสต๊อก"}</td></tr>)}</tbody></table></div> : <Empty text="ยังไม่มีรายการรับสินค้า" />}</>}</section></WarehousePageTemplate>;
}
