"use client";

import { useCallback, useRef, useState, type FormEvent } from "react";
import WarehousePageTemplate from "@/app/warehouse/_components/WarehousePageTemplate";
import { warehouseApi, type CatalogItem } from "@/lib/api/warehouse";
import { button, Empty, Field, input, message, Notice, panel, subtleButton, useRemote } from "./Ui";

export default function StockScreen({ initialTab = "balances" }: { initialTab?: "balances" | "ledger" }) {
  const [tab, setTab] = useState<"balances" | "ledger">(initialTab);
  const [warehouseFilter, setWarehouseFilter] = useState("");
  const [failure, setFailure] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const busyRef = useRef(false);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [me, balances, ledger, warehouses, products] = await Promise.all([warehouseApi.me(), warehouseApi.balances(), warehouseApi.ledger(), warehouseApi.catalog("warehouses"), warehouseApi.catalog("products")]); return { me, balances, ledger, warehouses, products }; }, []);
  const { data, loading, error, refresh } = useRemote(load);
  const save = async (body: Record<string, unknown>) => { if (busyRef.current) return; busyRef.current = true; setBusy(true); setFailure(null); setSuccess(null); try { await warehouseApi.createStockDocument(body); setSuccess("บันทึกการเคลื่อนไหวแล้ว"); await refresh(); } catch (cause) { setFailure(message(cause)); } finally { busyRef.current = false; setBusy(false); } };
  const reverse = async (documentId: number) => { const reason = window.prompt(`เหตุผลที่ต้องกลับรายการเอกสาร #${documentId}`); if (!reason?.trim()) return; setFailure(null); setSuccess(null); try { await warehouseApi.reverseStockDocument(documentId, reason.trim()); setSuccess("กลับรายการแล้ว"); await refresh(); } catch (cause) { setFailure(message(cause)); } };
  const balances = data?.balances.filter((item) => !warehouseFilter || String(item.warehouse_id) === warehouseFilter) ?? [];
  const ledger = data?.ledger.filter((item) => !warehouseFilter || String(item.warehouse_id) === warehouseFilter) ?? [];
  return <WarehousePageTemplate titleEn="Stock" titleTh="ยอดและประวัติสต๊อก" routePath="/warehouse/stock" iconName="layers">
    {busy && <Notice>กำลังบันทึกการเคลื่อนไหว...</Notice>}
    <div className="flex flex-wrap gap-2"><button className={tab === "balances" ? button : subtleButton} onClick={() => setTab("balances")}>ยอดคงเหลือ</button><button className={tab === "ledger" ? button : subtleButton} onClick={() => setTab("ledger")}>การเคลื่อนไหว</button><select className={`${input} max-w-64`} value={warehouseFilter} onChange={(event) => setWarehouseFilter(event.target.value)}><option value="">ทุกคลังที่มีสิทธิ์</option>{data?.warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    {error && <Notice tone="error">{error}</Notice>}{failure && <Notice tone="error">{failure}</Notice>}{success && <Notice tone="success">{success}</Notice>}{loading && <p>กำลังโหลดข้อมูล...</p>}
    {data && <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_350px]"><section className={panel}>{tab === "balances" ? <><h2 className="mb-4 text-lg font-bold">ยอดคงเหลือ</h2>{balances.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 dark:border-white/10"><th className="pb-2">สินค้า</th><th>สาขา / คลัง</th><th className="text-right">จำนวน</th></tr></thead><tbody>{balances.map((item) => <tr key={`${item.warehouse_id}-${item.product_id}`} className="border-b border-slate-100 dark:border-white/10"><td className="py-3">{item.sku} · {item.product_name}</td><td>{item.branch_name} / {item.warehouse_name}</td><td className="text-right font-semibold">{item.quantity} {item.unit_code}</td></tr>)}</tbody></table></div> : <Empty text="ยังไม่มียอดสต๊อก" />}</> : <><h2 className="mb-4 text-lg font-bold">ประวัติเคลื่อนไหว</h2>{ledger.length ? <div className="space-y-2">{ledger.map((item) => <div key={item.id} className="flex flex-wrap justify-between gap-3 border-b border-slate-100 py-2 text-sm dark:border-white/10"><span>{item.sku} · {item.product_name}<small className="block text-slate-500">{item.record_no} · {item.warehouse_name} · {new Date(item.occurred_at).toLocaleString("th-TH")}</small></span><div className="flex items-center gap-2"><strong className={Number(item.quantity_delta) >= 0 ? "text-emerald-600" : "text-rose-600"}>{Number(item.quantity_delta) > 0 ? "+" : ""}{item.quantity_delta}</strong>{["ADMIN", "CEO", "MANAGER"].includes(data.me.role) && item.kind !== "REVERSAL" && <button className="text-xs text-rose-600 underline" onClick={() => void reverse(item.document_id)}>กลับรายการ</button>}</div></div>)}</div> : <Empty text="ยังไม่มีรายการเคลื่อนไหว" />}</>}</section>{["ADMIN", "CEO", "MANAGER"].includes(data.me.role) && <StockForm warehouses={data.warehouses} products={data.products} onSave={save} />}</div>}
  </WarehousePageTemplate>;
}

function StockForm({ warehouses, products, onSave }: { warehouses: CatalogItem[]; products: CatalogItem[]; onSave: (body: Record<string, unknown>) => void }) {
  const [kind, setKind] = useState<"TRANSFER" | "ISSUE" | "ADJUSTMENT">("TRANSFER"); const [warehouseId, setWarehouseId] = useState(""); const [destination, setDestination] = useState(""); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState(""); const [reason, setReason] = useState(""); const [serials, setSerials] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); onSave({ kind, warehouseId: Number(warehouseId), ...(kind === "TRANSFER" ? { destinationWarehouseId: Number(destination) } : {}), reason, lines: [{ productId: Number(productId), ...(kind === "ADJUSTMENT" ? { quantityDelta: quantity } : { quantity }), serialNumbers: serials.split(/[,\n]/).map((item) => item.trim()).filter(Boolean) }] }); };
  return <form className={`${panel} space-y-3 self-start`} onSubmit={submit}><h2 className="text-lg font-bold">บันทึกการเคลื่อนไหว</h2><Field label="ประเภท"><select className={input} value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="TRANSFER">โอนระหว่างคลัง</option><option value="ISSUE">จ่ายออก</option><option value="ADJUSTMENT">ปรับยอด</option></select></Field><Field label="คลังต้นทาง"><select className={input} required value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)}><option value="">เลือกคลัง</option>{warehouses.filter((item) => item.active !== false).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>{kind === "TRANSFER" && <Field label="คลังปลายทาง"><select className={input} required value={destination} onChange={(event) => setDestination(event.target.value)}><option value="">เลือกคลัง</option>{warehouses.filter((item) => item.active !== false && String(item.id) !== warehouseId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>}<Field label="สินค้า"><select className={input} required value={productId} onChange={(event) => setProductId(event.target.value)}><option value="">เลือกสินค้า</option>{products.filter((item) => item.active !== false).map((item) => <option key={item.id} value={item.id}>{item.sku} · {item.name}</option>)}</select></Field><Field label={kind === "ADJUSTMENT" ? "ผลต่างจำนวน (+/-)" : "จำนวน"}><input className={input} required type="number" step="0.001" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></Field><Field label="เหตุผล"><textarea className={input} required value={reason} onChange={(event) => setReason(event.target.value)} /></Field><Field label="Serial (คั่นด้วยจุลภาค หากสินค้าใช้ Serial)"><textarea className={input} value={serials} onChange={(event) => setSerials(event.target.value)} /></Field><button className={button}>บันทึก</button></form>;
}
