import type {
  AdminUserRecord,
  CanonicalRole,
  FacilityRecord,
  WarehouseLocationRecord,
  DepartmentRecord,
  ProductCategoryRecord,
  BrandRecord,
  UnitOfMeasureRecord,
  ReasonCodeRecord,
  ProductRecord,
  SafetyStockRuleRecord,
  StockBalanceRecord,
  StockLedgerRecord,
  RoleAssignmentHistory,
} from "./types";

export const CANONICAL_ROLES: CanonicalRole[] = [
  {
    id: "role-1",
    code: "SYSTEM_ADMINISTRATOR",
    name: "System Administrator",
    nameTh: "ผู้ดูแลระบบสูงสุด",
    description: "ทุก permission และเข้าถึงทุก facility",
    isSystemAdmin: true,
    permissions: [
      "admin.users.read",
      "admin.users.manage",
      "admin.roles.read",
      "admin.roles.manage",
      "admin.facilities.manage",
      "stock.read",
      "stock.manage",
      "transfer.approve",
      "audit.read",
    ],
  },
  {
    id: "role-2",
    code: "HQ_AREA_MANAGER",
    name: "HQ Area Manager",
    nameTh: "ผู้จัดการพื้นที่ส่วนกลาง",
    description: "ดู facility/product, ดู stock, อนุมัติ transfer, จัดการ shipment/claim/report",
    permissions: [
      "facility.read",
      "product.read",
      "stock.read",
      "transfer.approve",
      "shipment.manage",
      "claim.manage",
      "report.view",
    ],
  },
  {
    id: "role-3",
    code: "WAREHOUSE_MANAGER",
    name: "Warehouse Manager",
    nameTh: "ผู้จัดการคลังสินค้า",
    description: "จัดการ receive, putaway, move, stock adjustment, transfer, picking, packing, shipment",
    permissions: [
      "inbound.receive",
      "inbound.putaway",
      "inventory.move",
      "stock.adjust",
      "transfer.create",
      "outbound.pick",
      "outbound.pack",
      "outbound.ship",
    ],
  },
  {
    id: "role-4",
    code: "STOCK_CONTROLLER",
    name: "Stock Controller",
    nameTh: "เจ้าหน้าที่ควบคุมสต็อก",
    description: "รับสินค้า, putaway, ย้าย stock, ขอปรับ stock, stock count",
    permissions: [
      "inbound.receive",
      "inbound.putaway",
      "inventory.move",
      "stock.request_adjust",
      "stock.count",
      "stock.read",
    ],
  },
  {
    id: "role-5",
    code: "PICKER_PACKER",
    name: "Picker & Packer",
    nameTh: "พนักงานหยิบและแพ็คสินค้า",
    description: "ดูและปฏิบัติงาน picking/packing",
    permissions: [
      "outbound.pick",
      "outbound.pack",
      "stock.read",
    ],
  },
  {
    id: "role-6",
    code: "BRANCH_REQUESTER",
    name: "Branch Requester",
    nameTh: "ผู้ขอเบิกประจำสาขา",
    description: "ดูสินค้า/stock และสร้าง transfer request",
    permissions: [
      "product.read",
      "stock.read",
      "transfer.request",
    ],
  },
  {
    id: "role-7",
    code: "BRANCH_RECEIVER",
    name: "Branch Receiver",
    nameTh: "ผู้ตรวจรับประจำสาขา",
    description: "รับ transfer, จัดการ receipt และ claim",
    permissions: [
      "transfer.receive",
      "receipt.manage",
      "claim.create",
    ],
  },
  {
    id: "role-8",
    code: "CLAIM_OFFICER",
    name: "Claim Officer",
    nameTh: "เจ้าหน้าที่เคลมสินค้า",
    description: "ดูและจัดการ claim รวมถึง report",
    permissions: [
      "claim.manage",
      "claim.read",
      "report.view",
    ],
  },
  {
    id: "role-9",
    code: "AUDITOR",
    name: "Auditor",
    nameTh: "ผู้ตรวจสอบระบบ",
    description: "อ่านข้อมูล product, stock, ledger, transfer, shipment, receipt, claim, report และ audit",
    permissions: [
      "product.read",
      "stock.read",
      "ledger.read",
      "transfer.read",
      "shipment.read",
      "receipt.read",
      "claim.read",
      "report.view",
      "audit.read",
    ],
  },
];

export const INITIAL_USERS: AdminUserRecord[] = [
  {
    id: "usr-001",
    name: "Johnathan Doe",
    email: "j.doe@dawh.com",
    emailVerified: true,
    accountStatus: "ACTIVE",
    profileComplete: true,
    username: "johndoe",
    facility: { id: "fac-01", code: "WH-BKK-01", name: "Bangkok Central Distribution Hub" },
    department: { id: "dept-01", code: "IT-SYS", name: "System Operations" },
    roles: [
      {
        assignmentId: "asg-01",
        roleId: "role-1",
        code: "SYSTEM_ADMINISTRATOR",
        name: "System Administrator",
        validFrom: "2026-01-01T00:00:00Z",
        validUntil: null,
      },
    ],
    facilityScopes: [
      {
        id: "sc-01",
        facilityId: "fac-01",
        facilityCode: "WH-BKK-01",
        scopeType: "ADMIN",
        validFrom: "2026-01-01T00:00:00Z",
        validUntil: null,
        version: 1,
      },
    ],
    createdAt: "2025-11-15T08:30:00Z",
  },
  {
    id: "usr-002",
    name: "Sarah Jenkins",
    email: "s.jenkins@dawh.com",
    emailVerified: true,
    accountStatus: "ACTIVE",
    profileComplete: true,
    username: "sjenkins",
    facility: { id: "fac-02", code: "WH-CNX-01", name: "Chiang Mai Regional Hub" },
    department: { id: "dept-02", code: "WH-OPS", name: "Warehouse Operations" },
    roles: [
      {
        assignmentId: "asg-02",
        roleId: "role-3",
        code: "WAREHOUSE_MANAGER",
        name: "Warehouse Manager",
        validFrom: "2026-02-01T00:00:00Z",
        validUntil: "2026-12-31T23:59:59Z",
      },
    ],
    facilityScopes: [
      {
        id: "sc-02",
        facilityId: "fac-02",
        facilityCode: "WH-CNX-01",
        scopeType: "APPROVE",
        validFrom: "2026-02-01T00:00:00Z",
        validUntil: null,
        version: 2,
      },
    ],
    createdAt: "2026-01-10T09:15:00Z",
  },
  {
    id: "usr-003",
    name: "Somchai Prasert",
    email: "somchai.p@dawh.com",
    emailVerified: true,
    accountStatus: "ACTIVE",
    profileComplete: true,
    username: "somchaip",
    facility: { id: "fac-03", code: "BR-KKN-01", name: "Khon Kaen Branch Facility" },
    department: { id: "dept-03", code: "LOG-INV", name: "Inventory Control" },
    roles: [
      {
        assignmentId: "asg-03",
        roleId: "role-4",
        code: "STOCK_CONTROLLER",
        name: "Stock Controller",
        validFrom: "2026-03-01T00:00:00Z",
        validUntil: null,
      },
    ],
    facilityScopes: [
      {
        id: "sc-03",
        facilityId: "fac-03",
        facilityCode: "BR-KKN-01",
        scopeType: "OPERATE",
        validFrom: "2026-03-01T00:00:00Z",
        validUntil: null,
        version: 1,
      },
    ],
    createdAt: "2026-02-20T11:00:00Z",
  },
  {
    id: "usr-004",
    name: "Wichai Rattana",
    email: "wichai.r@dawh.com",
    emailVerified: false,
    accountStatus: "SUSPENDED",
    statusReason: "อยู่ระหว่างการสอบสวนข้อผิดพลาดทางขั้นตอนตรวจนับสินค้า",
    profileComplete: false,
    username: "wichair",
    facility: { id: "fac-01", code: "WH-BKK-01", name: "Bangkok Central Distribution Hub" },
    department: { id: "dept-02", code: "WH-OPS", name: "Warehouse Operations" },
    roles: [
      {
        assignmentId: "asg-04",
        roleId: "role-5",
        code: "PICKER_PACKER",
        name: "Picker & Packer",
        validFrom: "2026-01-15T00:00:00Z",
        validUntil: "2026-08-30T00:00:00Z",
      },
    ],
    facilityScopes: [
      {
        id: "sc-04",
        facilityId: "fac-01",
        facilityCode: "WH-BKK-01",
        scopeType: "READ",
        validFrom: "2026-01-15T00:00:00Z",
        validUntil: null,
        version: 1,
      },
    ],
    createdAt: "2026-01-12T14:40:00Z",
  },
  {
    id: "usr-005",
    name: "Ploy Thanakorn",
    email: "ploy.t@dawh.com",
    emailVerified: true,
    accountStatus: "TERMINATED",
    statusReason: "สิ้นสุดสัญญาจ้างตามระยะเวลาที่กำหนด (Offboarded)",
    profileComplete: true,
    username: "ployt",
    facility: { id: "fac-04", code: "BR-SRT-01", name: "Surat Thani Branch Facility" },
    department: { id: "dept-04", code: "LOG-CLAIM", name: "Quality Assurance & Claims" },
    roles: [
      {
        assignmentId: "asg-05",
        roleId: "role-8",
        code: "CLAIM_OFFICER",
        name: "Claim Officer",
        validFrom: "2025-10-01T00:00:00Z",
        validUntil: "2026-06-30T23:59:59Z",
      },
    ],
    facilityScopes: [],
    createdAt: "2025-09-28T10:00:00Z",
  },
];

export const INITIAL_ROLE_HISTORY: RoleAssignmentHistory[] = [
  {
    id: "hist-01",
    userId: "usr-001",
    userName: "Johnathan Doe",
    roleCode: "SYSTEM_ADMINISTRATOR",
    roleName: "System Administrator",
    action: "ASSIGN",
    validFrom: "2026-01-01T00:00:00Z",
    validUntil: null,
    reason: "Initial enterprise founding deployment",
    performedBy: "SYSTEM",
    timestamp: "2026-01-01T00:00:00Z",
  },
  {
    id: "hist-02",
    userId: "usr-002",
    userName: "Sarah Jenkins",
    roleCode: "WAREHOUSE_MANAGER",
    roleName: "Warehouse Manager",
    action: "ASSIGN",
    validFrom: "2026-02-01T00:00:00Z",
    validUntil: "2026-12-31T23:59:59Z",
    reason: "Promotion to regional facility supervisor",
    performedBy: "Johnathan Doe",
    timestamp: "2026-02-01T09:00:00Z",
  },
  {
    id: "hist-03",
    userId: "usr-004",
    userName: "Wichai Rattana",
    roleCode: "STOCK_CONTROLLER",
    roleName: "Stock Controller",
    action: "REVOKE",
    validFrom: "2026-01-15T00:00:00Z",
    validUntil: "2026-04-10T00:00:00Z",
    reason: "Demoted to picker/packer pending operational review",
    performedBy: "Sarah Jenkins",
    timestamp: "2026-04-10T15:20:00Z",
  },
];

export const INITIAL_FACILITIES: FacilityRecord[] = [
  {
    id: "fac-01",
    code: "WH-BKK-01",
    name: "Bangkok Central Distribution Hub",
    type: "CENTRAL_WAREHOUSE",
    address: "101 Logistics Boulevard, Bang Na, Bangkok 10260",
    province: "Bangkok",
    latitude: 13.6682,
    longitude: 100.6341,
    manager: "Johnathan Doe",
    isActive: true,
  },
  {
    id: "fac-02",
    code: "WH-CNX-01",
    name: "Chiang Mai Regional Hub",
    type: "CENTRAL_WAREHOUSE",
    address: "88 Superhighway Road, San Sai, Chiang Mai 50210",
    province: "Chiang Mai",
    latitude: 18.7904,
    longitude: 98.9847,
    manager: "Sarah Jenkins",
    isActive: true,
  },
  {
    id: "fac-03",
    code: "BR-KKN-01",
    name: "Khon Kaen Branch Facility",
    type: "BRANCH",
    address: "45 Mittraphap Road, Mueang, Khon Kaen 40000",
    province: "Khon Kaen",
    latitude: 16.4322,
    longitude: 102.8236,
    manager: "Somchai Prasert",
    isActive: true,
  },
  {
    id: "fac-04",
    code: "BR-SRT-01",
    name: "Surat Thani Branch Facility",
    type: "BRANCH",
    address: "12 Karunrat Road, Mueang, Surat Thani 84000",
    province: "Surat Thani",
    latitude: 9.1382,
    longitude: 99.3217,
    manager: "Ploy Thanakorn",
    isActive: false,
  },
];

export const INITIAL_LOCATIONS: WarehouseLocationRecord[] = [
  {
    id: "loc-01",
    facilityId: "fac-01",
    facilityCode: "WH-BKK-01",
    code: "ZONE-A",
    name: "High-Velocity Ambient Zone",
    type: "Zone",
    status: "ACTIVE",
    parentId: null,
    path: "ZONE-A",
    depth: 1,
  },
  {
    id: "loc-02",
    facilityId: "fac-01",
    facilityCode: "WH-BKK-01",
    code: "AISLE-01",
    name: "Aisle 01 North",
    type: "Aisle",
    status: "ACTIVE",
    parentId: "loc-01",
    path: "ZONE-A/AISLE-01",
    depth: 2,
  },
  {
    id: "loc-03",
    facilityId: "fac-01",
    facilityCode: "WH-BKK-01",
    code: "RACK-01A",
    name: "Heavy Duty Pallet Rack 01A",
    type: "Rack",
    status: "ACTIVE",
    parentId: "loc-02",
    path: "ZONE-A/AISLE-01/RACK-01A",
    depth: 3,
  },
  {
    id: "loc-04",
    facilityId: "fac-01",
    facilityCode: "WH-BKK-01",
    code: "BIN-01A-101",
    name: "Pick Bin 101 Ground Floor",
    type: "Bin",
    status: "ACTIVE",
    parentId: "loc-03",
    path: "ZONE-A/AISLE-01/RACK-01A/BIN-01A-101",
    depth: 4,
  },
  {
    id: "loc-05",
    facilityId: "fac-01",
    facilityCode: "WH-BKK-01",
    code: "RCV-DOCK-1",
    name: "Receiving Inbound Dock Bay 1",
    type: "Receiving",
    status: "ACTIVE",
    parentId: null,
    path: "RCV-DOCK-1",
    depth: 1,
  },
  {
    id: "loc-06",
    facilityId: "fac-01",
    facilityCode: "WH-BKK-01",
    code: "QR-SEC-01",
    name: "Quarantine Containment Area",
    type: "Quarantine",
    status: "BLOCKED",
    parentId: null,
    path: "QR-SEC-01",
    depth: 1,
  },
  {
    id: "loc-07",
    facilityId: "fac-02",
    facilityCode: "WH-CNX-01",
    code: "ZONE-NORTH",
    name: "Primary Storage Northern Hall",
    type: "Zone",
    status: "ACTIVE",
    parentId: null,
    path: "ZONE-NORTH",
    depth: 1,
  },
];

export const INITIAL_DEPARTMENTS: DepartmentRecord[] = [
  {
    id: "dept-01",
    code: "IT-SYS",
    name: "System Operations & Infrastructure",
    nameTh: "ฝ่ายระบบโครงสร้างพื้นฐานและเทคโนโลยี",
    manager: "Johnathan Doe",
    isActive: true,
  },
  {
    id: "dept-02",
    code: "WH-OPS",
    name: "Warehouse Fulfillment Operations",
    nameTh: "ฝ่ายปฏิบัติการคลังสินค้าและการจัดส่ง",
    manager: "Sarah Jenkins",
    isActive: true,
  },
  {
    id: "dept-03",
    code: "LOG-INV",
    name: "Inventory Governance & Control",
    nameTh: "ฝ่ายควบคุมและตรวจสอบสินค้าคงคลัง",
    manager: "Somchai Prasert",
    isActive: true,
  },
  {
    id: "dept-04",
    code: "LOG-CLAIM",
    name: "Claims & Customer Dispute Resolution",
    nameTh: "ฝ่ายรับเรื่องและบริหารจัดการข้อพิพาทเคลม",
    manager: "Ploy Thanakorn",
    isActive: true,
  },
];

export const INITIAL_CATEGORIES: ProductCategoryRecord[] = [
  {
    id: "cat-01",
    code: "ELEC",
    nameTh: "อุปกรณ์อิเล็กทรอนิกส์และคอมพิวเตอร์",
    nameEn: "Electronics & Computing",
    parentId: null,
    depth: 1,
  },
  {
    id: "cat-02",
    code: "ELEC-SRV",
    nameTh: "อุปกรณ์เซิร์ฟเวอร์และเครือข่าย",
    nameEn: "Servers & Network Equipment",
    parentId: "cat-01",
    depth: 2,
  },
  {
    id: "cat-03",
    code: "IND-TOOL",
    nameTh: "เครื่องมือช่างและอุปกรณ์อุตสาหกรรม",
    nameEn: "Industrial Tools & Hardware",
    parentId: null,
    depth: 1,
  },
  {
    id: "cat-04",
    code: "PACK-MAT",
    nameTh: "วัสดุบรรจุภัณฑ์และการจัดส่ง",
    nameEn: "Packaging Materials & Supplies",
    parentId: null,
    depth: 1,
  },
];

export const INITIAL_BRANDS: BrandRecord[] = [
  { id: "b-01", code: "DAWH-PRO", name: "DAWH Pro Line", country: "Thailand" },
  { id: "b-02", code: "CISCO", name: "Cisco Systems", country: "United States" },
  { id: "b-03", code: "SCHNEIDER", name: "Schneider Electric", country: "France" },
  { id: "b-04", code: "BOSCH", name: "Robert Bosch", country: "Germany" },
];

export const INITIAL_UOMS: UnitOfMeasureRecord[] = [
  { id: "uom-01", code: "PCS", nameTh: "ชิ้น", nameEn: "Pieces", symbol: "pcs" },
  { id: "uom-02", code: "BOX", nameTh: "กล่อง", nameEn: "Box", symbol: "box" },
  { id: "uom-03", code: "CTN", nameTh: "ลัง", nameEn: "Carton", symbol: "ctn" },
  { id: "uom-04", code: "PLT", nameTh: "พาเลท", nameEn: "Pallet", symbol: "plt" },
  { id: "uom-05", code: "KG", nameTh: "กิโลกรัม", nameEn: "Kilogram", symbol: "kg" },
];

export const INITIAL_REASON_CODES: ReasonCodeRecord[] = [
  {
    id: "rc-01",
    code: "ADJ-CYCLE",
    nameTh: "ปรับยอดตามรอบการตรวจนับประจำสัปดาห์",
    nameEn: "Weekly Cycle Count Variance",
    category: "ADJUSTMENT",
    description: "ส่วนต่างปริมาณจากการสแกนนับจริงในรอบตรวจนับ",
  },
  {
    id: "rc-02",
    code: "CLM-TRANSIT",
    nameTh: "สินค้าเสียหายระหว่างการขนส่ง",
    nameEn: "Transit Collision Damage",
    category: "CLAIM",
    description: "กล่องบรรจุภัณฑ์บุบหรือแตกระหว่างการเคลื่อนย้าย",
  },
  {
    id: "rc-03",
    code: "OPS-EXPIRE",
    nameTh: "สินค้าหมดอายุตามข้อกำหนดควบคุมคุณภาพ",
    nameEn: "Shelf Life Expiration",
    category: "OPERATIONAL",
    description: "อายุสินค้าเกินระยะเวลาที่ได้รับอนุญาตให้จัดจำหน่าย",
  },
];

export const INITIAL_PRODUCTS: ProductRecord[] = [
  {
    id: "prod-001",
    sku: "SRV-RACK-42U",
    nameTh: "ตู้เซิร์ฟเวอร์มาตรฐานความปลอดภัย 42U",
    nameEn: "Enterprise 42U Server Rack Enclosure",
    categoryId: "cat-02",
    categoryName: "Servers & Network Equipment",
    brandId: "b-03",
    brandName: "Schneider Electric",
    baseUnit: "PCS",
    trackingMethod: "SERIAL",
    pickingStrategy: "FIFO",
    weightKg: 125.0,
    dimensionsCm: { width: 60, length: 100, height: 200 },
    shelfLifeDays: 0,
    storageCondition: "Dry Ambient 20-25°C",
    isActive: true,
    units: [
      { id: "pu-01", unitCode: "BOX", unitName: "กล่องบรรจุ", multiplier: 1 },
      { id: "pu-02", unitCode: "PLT", unitName: "พาเลทส่งมอบ", multiplier: 2 },
    ],
    barcodes: [
      { id: "bc-01", barcode: "8859012300018", unitCode: "PCS", isPrimary: true },
      { id: "bc-02", barcode: "8859012300025", unitCode: "PLT", isPrimary: false },
    ],
  },
  {
    id: "prod-002",
    sku: "NET-SW-GIGA24",
    nameTh: "สวิตช์เครือข่ายความเร็วสูงกิกะบิต 24 พอร์ต",
    nameEn: "Managed 24-Port Gigabit Ethernet Switch",
    categoryId: "cat-02",
    categoryName: "Servers & Network Equipment",
    brandId: "b-02",
    brandName: "Cisco Systems",
    baseUnit: "PCS",
    trackingMethod: "SERIAL",
    pickingStrategy: "FIFO",
    weightKg: 4.5,
    dimensionsCm: { width: 44, length: 28, height: 4.4 },
    shelfLifeDays: 0,
    storageCondition: "Dry Ambient 18-24°C",
    isActive: true,
    units: [
      { id: "pu-03", unitCode: "CTN", unitName: "ลังบรรจุ 5 ตัว", multiplier: 5 },
    ],
    barcodes: [
      { id: "bc-03", barcode: "8859012300032", unitCode: "PCS", isPrimary: true },
    ],
  },
  {
    id: "prod-003",
    sku: "IND-BAT-12V100",
    nameTh: "แบตเตอรี่สำรองระบบไฟฟ้าสำรอง 12V 100Ah",
    nameEn: "Deep Cycle UPS Backup Battery 12V 100Ah",
    categoryId: "cat-03",
    categoryName: "Industrial Tools & Hardware",
    brandId: "b-01",
    brandName: "DAWH Pro Line",
    baseUnit: "PCS",
    trackingMethod: "LOT",
    pickingStrategy: "FEFO",
    weightKg: 31.0,
    dimensionsCm: { width: 17, length: 33, height: 22 },
    shelfLifeDays: 730,
    storageCondition: "Ventilated Cool Store 15-20°C",
    isActive: true,
    units: [
      { id: "pu-04", unitCode: "PLT", unitName: "พาเลทอุตสาหกรรม 20 ลูก", multiplier: 20 },
    ],
    barcodes: [
      { id: "bc-04", barcode: "8859012300049", unitCode: "PCS", isPrimary: true },
    ],
  },
  {
    id: "prod-004",
    sku: "PKG-WRAP-500M",
    nameTh: "ฟิล์มยืดพันพาเลทเกรดหนาพิเศษ 500 เมตร",
    nameEn: "Heavy-Duty Pallet Stretch Film 500m",
    categoryId: "cat-04",
    categoryName: "Packaging Materials & Supplies",
    brandId: "b-01",
    brandName: "DAWH Pro Line",
    baseUnit: "PCS",
    trackingMethod: "NONE",
    pickingStrategy: "FIFO",
    weightKg: 2.8,
    dimensionsCm: { width: 15, length: 15, height: 50 },
    shelfLifeDays: 0,
    storageCondition: "Dry Store",
    isActive: true,
    units: [
      { id: "pu-05", unitCode: "BOX", unitName: "กล่อง 6 ม้วน", multiplier: 6 },
    ],
    barcodes: [
      { id: "bc-05", barcode: "8859012300056", unitCode: "PCS", isPrimary: true },
    ],
  },
];

export const INITIAL_SAFETY_STOCK_RULES: SafetyStockRuleRecord[] = [
  {
    id: "ssr-01",
    facilityId: "fac-01",
    facilityCode: "WH-BKK-01",
    facilityName: "Bangkok Central Distribution Hub",
    productId: "prod-001",
    productSku: "SRV-RACK-42U",
    productName: "ตู้เซิร์ฟเวอร์มาตรฐานความปลอดภัย 42U",
    minQty: 10,
    maxQty: 100,
    reorderPoint: 25,
    safetyQty: 15,
    currentBalance: 42,
  },
  {
    id: "ssr-02",
    facilityId: "fac-01",
    facilityCode: "WH-BKK-01",
    facilityName: "Bangkok Central Distribution Hub",
    productId: "prod-002",
    productSku: "NET-SW-GIGA24",
    productName: "สวิตช์เครือข่ายความเร็วสูงกิกะบิต 24 พอร์ต",
    minQty: 20,
    maxQty: 200,
    reorderPoint: 40,
    safetyQty: 30,
    currentBalance: 24, // Warning: near reorder point
  },
  {
    id: "ssr-03",
    facilityId: "fac-02",
    facilityCode: "WH-CNX-01",
    facilityName: "Chiang Mai Regional Hub",
    productId: "prod-003",
    productSku: "IND-BAT-12V100",
    productName: "แบตเตอรี่สำรองระบบไฟฟ้าสำรอง 12V 100Ah",
    minQty: 15,
    maxQty: 120,
    reorderPoint: 35,
    safetyQty: 20,
    currentBalance: 8, // Danger: below safety qty!
  },
  {
    id: "ssr-04",
    facilityId: "fac-03",
    facilityCode: "BR-KKN-01",
    facilityName: "Khon Kaen Branch Facility",
    productId: "prod-004",
    productSku: "PKG-WRAP-500M",
    productName: "ฟิล์มยืดพันพาเลทเกรดหนาพิเศษ 500 เมตร",
    minQty: 50,
    maxQty: 500,
    reorderPoint: 100,
    safetyQty: 80,
    currentBalance: 320,
  },
];

export const INITIAL_STOCK_BALANCES: StockBalanceRecord[] = [
  {
    id: "stk-01",
    facilityCode: "WH-BKK-01",
    facilityName: "Bangkok Central Hub",
    locationCode: "BIN-01A-101",
    sku: "SRV-RACK-42U",
    productName: "ตู้เซิร์ฟเวอร์มาตรฐานความปลอดภัย 42U",
    baseUnit: "pcs",
    onHand: 42,
    reserved: 8,
    available: 34,
    status: "USABLE",
    updatedAt: "2026-09-19T22:30:00Z",
  },
  {
    id: "stk-02",
    facilityCode: "WH-BKK-01",
    facilityName: "Bangkok Central Hub",
    locationCode: "BIN-01A-101",
    sku: "NET-SW-GIGA24",
    productName: "สวิตช์เครือข่ายความเร็วสูงกิกะบิต 24 พอร์ต",
    baseUnit: "pcs",
    onHand: 24,
    reserved: 10,
    available: 14,
    status: "USABLE",
    updatedAt: "2026-09-19T21:15:00Z",
  },
  {
    id: "stk-03",
    facilityCode: "WH-CNX-01",
    facilityName: "Chiang Mai Regional Hub",
    locationCode: "ZONE-NORTH",
    sku: "IND-BAT-12V100",
    productName: "แบตเตอรี่สำรองระบบไฟฟ้าสำรอง 12V 100Ah",
    baseUnit: "pcs",
    onHand: 8,
    reserved: 2,
    available: 6,
    status: "USABLE",
    updatedAt: "2026-09-19T18:45:00Z",
  },
  {
    id: "stk-04",
    facilityCode: "WH-BKK-01",
    facilityName: "Bangkok Central Hub",
    locationCode: "QR-SEC-01",
    sku: "IND-BAT-12V100",
    productName: "แบตเตอรี่สำรองระบบไฟฟ้าสำรอง 12V 100Ah",
    baseUnit: "pcs",
    onHand: 3,
    reserved: 0,
    available: 0,
    status: "QUARANTINE",
    updatedAt: "2026-09-19T16:20:00Z",
  },
  {
    id: "stk-05",
    facilityCode: "BR-KKN-01",
    facilityName: "Khon Kaen Branch",
    locationCode: "ZONE-DEFAULT",
    sku: "PKG-WRAP-500M",
    productName: "ฟิล์มยืดพันพาเลทเกรดหนาพิเศษ 500 เมตร",
    baseUnit: "pcs",
    onHand: 320,
    reserved: 40,
    available: 280,
    status: "USABLE",
    updatedAt: "2026-09-19T14:10:00Z",
  },
];

export const INITIAL_STOCK_LEDGER: StockLedgerRecord[] = [
  {
    id: "ldg-01",
    timestamp: "2026-09-19T22:30:00Z",
    facilityCode: "WH-BKK-01",
    referenceDoc: "GRN-202609-0091",
    transactionType: "RECEIVE",
    sku: "SRV-RACK-42U",
    productName: "ตู้เซิร์ฟเวอร์มาตรฐานความปลอดภัย 42U",
    qtyChange: +10,
    balanceAfter: 42,
    operatorName: "Johnathan Doe",
  },
  {
    id: "ldg-02",
    timestamp: "2026-09-19T21:15:00Z",
    facilityCode: "WH-BKK-01",
    referenceDoc: "TRF-OUT-0042",
    transactionType: "TRANSFER",
    sku: "NET-SW-GIGA24",
    productName: "สวิตช์เครือข่ายความเร็วสูงกิกะบิต 24 พอร์ต",
    qtyChange: -5,
    balanceAfter: 24,
    operatorName: "Sarah Jenkins",
  },
  {
    id: "ldg-03",
    timestamp: "2026-09-19T18:45:00Z",
    facilityCode: "WH-CNX-01",
    referenceDoc: "ADJ-2026-0012",
    transactionType: "ADJUST",
    sku: "IND-BAT-12V100",
    productName: "แบตเตอรี่สำรองระบบไฟฟ้าสำรอง 12V 100Ah",
    qtyChange: -2,
    balanceAfter: 8,
    operatorName: "Somchai Prasert",
  },
  {
    id: "ldg-04",
    timestamp: "2026-09-19T16:20:00Z",
    facilityCode: "WH-BKK-01",
    referenceDoc: "CLM-IN-0008",
    transactionType: "CLAIM",
    sku: "IND-BAT-12V100",
    productName: "แบตเตอรี่สำรองระบบไฟฟ้าสำรอง 12V 100Ah",
    qtyChange: +3,
    balanceAfter: 3,
    operatorName: "Ploy Thanakorn",
  },
];
