-- Baseline for the WMS foundation. IDs are generated by the application as UUIDv7.
-- IF NOT EXISTS allows this migration to adopt the already-provisioned database.

CREATE TABLE IF NOT EXISTS public.roles (
  id uuid PRIMARY KEY, code text NOT NULL UNIQUE CHECK (btrim(code) <> ''),
  name text NOT NULL CHECK (btrim(name) <> ''), description text,
  is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.permissions (
  id uuid PRIMARY KEY, code text NOT NULL UNIQUE CHECK (btrim(code) <> ''),
  module text NOT NULL CHECK (btrim(module) <> ''), description text NOT NULL,
  is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
  role_id uuid NOT NULL REFERENCES public.roles (id) ON DELETE CASCADE,
  permission_id uuid NOT NULL REFERENCES public.permissions (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid PRIMARY KEY, code text NOT NULL UNIQUE CHECK (btrim(code) <> ''),
  name text NOT NULL CHECK (btrim(name) <> ''), timezone text NOT NULL DEFAULT 'Asia/Bangkok',
  is_active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.facilities (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  code text NOT NULL CHECK (btrim(code) <> ''), name text NOT NULL CHECK (btrim(name) <> ''),
  facility_type text NOT NULL CHECK (facility_type IN ('CENTRAL_WAREHOUSE','BRANCH')),
  address_line_1 text, address_line_2 text, province text, district text, subdistrict text, postal_code text,
  latitude numeric(9,6) CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  longitude numeric(9,6) CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  is_active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (id, organization_id), UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS public.facility_routes (
  id uuid PRIMARY KEY, source_facility_id uuid NOT NULL REFERENCES public.facilities (id) ON DELETE RESTRICT,
  destination_facility_id uuid NOT NULL REFERENCES public.facilities (id) ON DELETE RESTRICT,
  distance_km numeric(12,3) CHECK (distance_km IS NULL OR distance_km >= 0),
  lead_time_minutes integer CHECK (lead_time_minutes IS NULL OR lead_time_minutes >= 0),
  priority integer NOT NULL DEFAULT 100 CHECK (priority > 0), is_active boolean NOT NULL DEFAULT true,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0), created_at timestamptz NOT NULL DEFAULT now(),
  created_by text REFERENCES public."user" (id) ON DELETE SET NULL, updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (source_facility_id, destination_facility_id), CHECK (source_facility_id <> destination_facility_id)
);

CREATE TABLE IF NOT EXISTS public.warehouse_locations (
  id uuid PRIMARY KEY, facility_id uuid NOT NULL REFERENCES public.facilities (id) ON DELETE RESTRICT,
  parent_id uuid, code text NOT NULL CHECK (btrim(code) <> ''), name text NOT NULL CHECK (btrim(name) <> ''),
  hierarchy_type text NOT NULL CHECK (hierarchy_type IN ('ZONE','AISLE','RACK','SHELF','BIN')),
  location_type text NOT NULL CHECK (location_type IN ('RECEIVING','STORAGE','PICKING','PACKING','DISPATCH','QUARANTINE','DAMAGED','RETURN','CLAIM_HOLDING')),
  path text NOT NULL, depth smallint NOT NULL DEFAULT 0 CHECK (depth >= 0),
  max_volume numeric(18,6) CHECK (max_volume IS NULL OR max_volume >= 0),
  max_weight numeric(18,6) CHECK (max_weight IS NULL OR max_weight >= 0),
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED','MAINTENANCE')),
  is_active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (id, facility_id), UNIQUE (facility_id, code), CHECK (parent_id IS NULL OR parent_id <> id),
  FOREIGN KEY (parent_id, facility_id) REFERENCES public.warehouse_locations (id, facility_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.user_role_assignments (
  id uuid PRIMARY KEY, user_id text NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
  role_id uuid NOT NULL REFERENCES public.roles (id) ON DELETE RESTRICT,
  valid_from timestamptz, valid_until timestamptz, assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by text REFERENCES public."user" (id) ON DELETE SET NULL, revoked_at timestamptz,
  revoked_by text REFERENCES public."user" (id) ON DELETE SET NULL, revoke_reason text,
  CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from)
);

CREATE TABLE IF NOT EXISTS public.user_facility_scopes (
  id uuid PRIMARY KEY, user_id text NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
  facility_id uuid NOT NULL REFERENCES public.facilities (id) ON DELETE CASCADE,
  scope_type text NOT NULL CHECK (scope_type IN ('READ','OPERATE','APPROVE','ADMIN')),
  valid_from timestamptz, valid_until timestamptz, created_at timestamptz NOT NULL DEFAULT now(),
  created_by text REFERENCES public."user" (id) ON DELETE SET NULL, updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text REFERENCES public."user" (id) ON DELETE SET NULL, UNIQUE (user_id, facility_id),
  CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from)
);

CREATE TABLE IF NOT EXISTS public.product_categories (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  parent_id uuid, code text NOT NULL CHECK (btrim(code) <> ''), name text NOT NULL CHECK (btrim(name) <> ''),
  description text, is_active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (id, organization_id), UNIQUE (organization_id, code), CHECK (parent_id IS NULL OR parent_id <> id),
  FOREIGN KEY (parent_id, organization_id) REFERENCES public.product_categories (id, organization_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.brands (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  code text NOT NULL CHECK (btrim(code) <> ''), name text NOT NULL CHECK (btrim(name) <> ''),
  is_active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (id, organization_id), UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS public.units_of_measure (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  code text NOT NULL CHECK (btrim(code) <> ''), name text NOT NULL CHECK (btrim(name) <> ''),
  decimal_scale smallint NOT NULL DEFAULT 0 CHECK (decimal_scale BETWEEN 0 AND 6),
  is_active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (id, organization_id), UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS public.products (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  sku text NOT NULL CHECK (btrim(sku) <> ''), name_th text NOT NULL CHECK (btrim(name_th) <> ''),
  name_en text, description text, category_id uuid, brand_id uuid, base_unit_id uuid NOT NULL,
  tracking_method text NOT NULL DEFAULT 'NONE' CHECK (tracking_method IN ('NONE','LOT','SERIAL')),
  picking_strategy text NOT NULL DEFAULT 'FIFO' CHECK (picking_strategy IN ('FIFO','FEFO')),
  weight_kg numeric(18,6) CHECK (weight_kg IS NULL OR weight_kg >= 0),
  length_cm numeric(18,6) CHECK (length_cm IS NULL OR length_cm >= 0),
  width_cm numeric(18,6) CHECK (width_cm IS NULL OR width_cm >= 0),
  height_cm numeric(18,6) CHECK (height_cm IS NULL OR height_cm >= 0),
  standard_cost numeric(18,2) CHECK (standard_cost IS NULL OR standard_cost >= 0),
  currency_code char(3) NOT NULL DEFAULT 'THB', shelf_life_days integer CHECK (shelf_life_days IS NULL OR shelf_life_days >= 0),
  storage_condition text, is_active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (organization_id, sku),
  FOREIGN KEY (category_id, organization_id) REFERENCES public.product_categories (id, organization_id) ON DELETE RESTRICT,
  FOREIGN KEY (brand_id, organization_id) REFERENCES public.brands (id, organization_id) ON DELETE RESTRICT,
  FOREIGN KEY (base_unit_id, organization_id) REFERENCES public.units_of_measure (id, organization_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.product_units (
  id uuid PRIMARY KEY, product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
  unit_id uuid NOT NULL REFERENCES public.units_of_measure (id) ON DELETE RESTRICT,
  base_quantity numeric(18,6) NOT NULL CHECK (base_quantity > 0),
  length_cm numeric(18,6) CHECK (length_cm IS NULL OR length_cm >= 0), width_cm numeric(18,6) CHECK (width_cm IS NULL OR width_cm >= 0),
  height_cm numeric(18,6) CHECK (height_cm IS NULL OR height_cm >= 0), weight_kg numeric(18,6) CHECK (weight_kg IS NULL OR weight_kg >= 0),
  is_active boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (product_id, unit_id)
);

CREATE TABLE IF NOT EXISTS public.product_barcodes (
  id uuid PRIMARY KEY, product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
  product_unit_id uuid REFERENCES public.product_units (id) ON DELETE RESTRICT, barcode text NOT NULL UNIQUE CHECK (btrim(barcode) <> ''),
  barcode_type text NOT NULL DEFAULT 'EAN_13' CHECK (barcode_type IN ('EAN_13','UPC_A','CODE_128','QR','INTERNAL')),
  is_primary boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(),
  created_by text REFERENCES public."user" (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.lots (
  id uuid PRIMARY KEY, product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE RESTRICT,
  lot_number text NOT NULL CHECK (btrim(lot_number) <> ''), manufactured_at date, expiry_date date,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','EXPIRED','BLOCKED')),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (product_id, lot_number), CHECK (manufactured_at IS NULL OR expiry_date IS NULL OR expiry_date >= manufactured_at)
);

CREATE TABLE IF NOT EXISTS public.serial_numbers (
  id uuid PRIMARY KEY, product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE RESTRICT,
  lot_id uuid REFERENCES public.lots (id) ON DELETE RESTRICT, serial_number text NOT NULL CHECK (btrim(serial_number) <> ''),
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','IN_TRANSIT','LOST','DAMAGED','RETIRED')),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(), updated_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (product_id, serial_number)
);

CREATE TABLE IF NOT EXISTS public.safety_stock_rules (
  id uuid PRIMARY KEY, facility_id uuid NOT NULL REFERENCES public.facilities (id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
  minimum_quantity numeric(18,6) NOT NULL DEFAULT 0 CHECK (minimum_quantity >= 0),
  maximum_quantity numeric(18,6), reorder_point numeric(18,6) NOT NULL DEFAULT 0 CHECK (reorder_point >= 0),
  safety_quantity numeric(18,6) NOT NULL DEFAULT 0 CHECK (safety_quantity >= 0),
  version integer NOT NULL DEFAULT 1 CHECK (version > 0), created_at timestamptz NOT NULL DEFAULT now(),
  created_by text REFERENCES public."user" (id) ON DELETE SET NULL, updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text REFERENCES public."user" (id) ON DELETE SET NULL, UNIQUE (facility_id, product_id),
  CHECK (maximum_quantity IS NULL OR maximum_quantity >= minimum_quantity)
);

CREATE TABLE IF NOT EXISTS public.reason_codes (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  domain text NOT NULL CHECK (btrim(domain) <> ''), code text NOT NULL CHECK (btrim(code) <> ''),
  name text NOT NULL CHECK (btrim(name) <> ''), description text, requires_note boolean NOT NULL DEFAULT false,
  requires_attachment boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0), created_at timestamptz NOT NULL DEFAULT now(),
  created_by text REFERENCES public."user" (id) ON DELETE SET NULL, updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text REFERENCES public."user" (id) ON DELETE SET NULL, UNIQUE (organization_id, domain, code)
);

CREATE TABLE IF NOT EXISTS public.document_sequences (
  organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  document_type text NOT NULL CHECK (btrim(document_type) <> ''), period char(6) NOT NULL CHECK (period ~ '^[0-9]{6}$'),
  last_value integer NOT NULL DEFAULT 0 CHECK (last_value >= 0), updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, document_type, period)
);

CREATE TABLE IF NOT EXISTS public.idempotency_keys (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  user_id text NOT NULL REFERENCES public."user" (id) ON DELETE RESTRICT, route_fingerprint text NOT NULL,
  idempotency_key text NOT NULL, request_hash text NOT NULL,
  status text NOT NULL DEFAULT 'PROCESSING' CHECK (status IN ('PROCESSING','COMPLETED','FAILED')),
  response_status integer CHECK (response_status IS NULL OR response_status BETWEEN 100 AND 599), response_body jsonb,
  created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, expires_at timestamptz NOT NULL,
  UNIQUE (organization_id, user_id, idempotency_key), CHECK (expires_at > created_at)
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  request_id text NOT NULL, actor_user_id text REFERENCES public."user" (id) ON DELETE SET NULL,
  action text NOT NULL CHECK (btrim(action) <> ''), entity_type text NOT NULL CHECK (btrim(entity_type) <> ''),
  entity_id uuid, facility_id uuid REFERENCES public.facilities (id) ON DELETE SET NULL,
  old_values jsonb, new_values jsonb, ip_address text, user_agent text, occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.outbox_events (
  id uuid PRIMARY KEY, aggregate_type text NOT NULL CHECK (btrim(aggregate_type) <> ''), aggregate_id uuid NOT NULL,
  event_type text NOT NULL CHECK (btrim(event_type) <> ''), payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(), available_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0), last_error text
);

CREATE TABLE IF NOT EXISTS public.attachments (
  id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  entity_type text NOT NULL CHECK (btrim(entity_type) <> ''), entity_id uuid NOT NULL,
  category text NOT NULL CHECK (btrim(category) <> ''), storage_bucket text NOT NULL CHECK (btrim(storage_bucket) <> ''),
  storage_object_key text NOT NULL CHECK (btrim(storage_object_key) <> ''), mime_type text NOT NULL,
  byte_size bigint NOT NULL CHECK (byte_size >= 0), checksum_sha256 text,
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACTIVE','DELETED')),
  created_at timestamptz NOT NULL DEFAULT now(), created_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  deleted_at timestamptz, deleted_by text REFERENCES public."user" (id) ON DELETE SET NULL,
  UNIQUE (storage_bucket, storage_object_key)
);

CREATE TABLE IF NOT EXISTS public.stock_balances (
  id uuid PRIMARY KEY, facility_id uuid NOT NULL REFERENCES public.facilities (id) ON DELETE RESTRICT,
  location_id uuid, product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE RESTRICT,
  lot_id uuid REFERENCES public.lots (id) ON DELETE RESTRICT, serial_id uuid REFERENCES public.serial_numbers (id) ON DELETE RESTRICT,
  shipment_id uuid, stock_status text NOT NULL CHECK (stock_status IN ('AVAILABLE','RESERVED','PICKED','PACKED','IN_TRANSIT','QUARANTINE','DAMAGED','CLAIM_PENDING','EXPIRED','LOST')),
  quantity numeric(18,6) NOT NULL CHECK (quantity >= 0), version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (location_id, facility_id) REFERENCES public.warehouse_locations (id, facility_id) ON DELETE RESTRICT,
  CONSTRAINT stock_balances_custody_check CHECK (
    (stock_status IN ('IN_TRANSIT','LOST') AND shipment_id IS NOT NULL AND location_id IS NULL) OR
    (stock_status NOT IN ('IN_TRANSIT','LOST') AND shipment_id IS NULL AND location_id IS NOT NULL)
  ),
  UNIQUE NULLS NOT DISTINCT (facility_id, location_id, shipment_id, product_id, lot_id, serial_id, stock_status)
);

CREATE TABLE IF NOT EXISTS public.inventory_transactions (
  id uuid PRIMARY KEY, transaction_no text NOT NULL UNIQUE CHECK (btrim(transaction_no) <> ''),
  organization_id uuid NOT NULL REFERENCES public.organizations (id) ON DELETE RESTRICT,
  transaction_type text NOT NULL CHECK (transaction_type IN ('RECEIVE','PUTAWAY','MOVE','RESERVE','RELEASE_RESERVATION','PICK','PACK','DISPATCH','RECEIVE_TRANSFER','QUARANTINE','CLAIM_HOLD','ADJUST','WRITE_OFF','RETURN','REVERSE')),
  reference_type text NOT NULL CHECK (btrim(reference_type) <> ''), reference_id uuid NOT NULL,
  reversal_of_id uuid REFERENCES public.inventory_transactions (id) ON DELETE RESTRICT,
  reason_code_id uuid REFERENCES public.reason_codes (id) ON DELETE RESTRICT, note text,
  occurred_at timestamptz NOT NULL, posted_at timestamptz NOT NULL DEFAULT now(),
  posted_by text NOT NULL REFERENCES public."user" (id) ON DELETE RESTRICT,
  idempotency_key_id uuid UNIQUE REFERENCES public.idempotency_keys (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.inventory_transaction_lines (
  id uuid PRIMARY KEY, transaction_id uuid NOT NULL REFERENCES public.inventory_transactions (id) ON DELETE RESTRICT,
  line_no integer NOT NULL CHECK (line_no > 0), facility_id uuid NOT NULL REFERENCES public.facilities (id) ON DELETE RESTRICT,
  location_id uuid REFERENCES public.warehouse_locations (id) ON DELETE RESTRICT,
  product_id uuid NOT NULL REFERENCES public.products (id) ON DELETE RESTRICT,
  lot_id uuid REFERENCES public.lots (id) ON DELETE RESTRICT, serial_id uuid REFERENCES public.serial_numbers (id) ON DELETE RESTRICT,
  shipment_id uuid, stock_status text NOT NULL CHECK (stock_status IN ('AVAILABLE','RESERVED','PICKED','PACKED','IN_TRANSIT','QUARANTINE','DAMAGED','CLAIM_PENDING','EXPIRED','LOST')),
  quantity_before numeric(18,6) NOT NULL CHECK (quantity_before >= 0), quantity_delta numeric(18,6) NOT NULL CHECK (quantity_delta <> 0),
  quantity_after numeric(18,6) NOT NULL CHECK (quantity_after >= 0), posted_at timestamptz NOT NULL,
  UNIQUE (transaction_id, line_no), CHECK (quantity_before + quantity_delta = quantity_after)
);

CREATE UNIQUE INDEX IF NOT EXISTS user_role_assignments_active_uk ON public.user_role_assignments (user_id, role_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS user_role_assignments_user_id_idx ON public.user_role_assignments (user_id);
CREATE INDEX IF NOT EXISTS user_facility_scopes_user_id_idx ON public.user_facility_scopes (user_id);
CREATE INDEX IF NOT EXISTS facilities_org_type_active_idx ON public.facilities (organization_id, facility_type, is_active);
CREATE INDEX IF NOT EXISTS products_org_active_idx ON public.products (organization_id, is_active);
CREATE UNIQUE INDEX IF NOT EXISTS product_barcodes_primary_per_product_uk ON public.product_barcodes (product_id) WHERE is_primary;
CREATE INDEX IF NOT EXISTS stock_balances_facility_product_status_idx ON public.stock_balances (facility_id, product_id, stock_status);
CREATE UNIQUE INDEX IF NOT EXISTS stock_balances_positive_serial_uk ON public.stock_balances (serial_id) WHERE serial_id IS NOT NULL AND quantity > 0;
CREATE INDEX IF NOT EXISTS inventory_transactions_org_posted_idx ON public.inventory_transactions (organization_id, posted_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS inventory_transaction_lines_product_facility_posted_idx ON public.inventory_transaction_lines (product_id, facility_id, posted_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS audit_logs_org_occurred_idx ON public.audit_logs (organization_id, occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS outbox_events_pending_idx ON public.outbox_events (available_at, id) WHERE published_at IS NULL;
CREATE INDEX IF NOT EXISTS idempotency_keys_expires_at_idx ON public.idempotency_keys (expires_at);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'roles','permissions','organizations','facilities','facility_routes','warehouse_locations',
    'user_facility_scopes','product_categories','brands','units_of_measure','products','product_units',
    'lots','serial_numbers','safety_stock_rules','reason_codes'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', table_name || '_set_updated_at', table_name);
    EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()', table_name || '_set_updated_at', table_name);
  END LOOP;
END;
$$;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'roles','permissions','role_permissions','organizations','facilities','facility_routes','warehouse_locations',
    'user_role_assignments','user_facility_scopes','product_categories','brands','units_of_measure','products',
    'product_units','product_barcodes','lots','serial_numbers','safety_stock_rules','reason_codes','document_sequences',
    'idempotency_keys','audit_logs','outbox_events','attachments','stock_balances','inventory_transactions','inventory_transaction_lines'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated', table_name);
  END LOOP;
END;
$$;
